### PR TITLE
Day 6 additional solution and typo fix

### PR DESCRIPTION
**Pull request by underlineGalaxy**
The other answers didn't really feel Pythonic, so I thought of sharing mine :P 
Also little typo fix in the end

### CODE REVIEW

**Comment by darkprinx** [comment]
> The other answers didn't really feel Pythonic, so I thought of sharing mine :P
> Also little typo fix in the end

Please let me know which answer's you didn't find pythonic. I believe you have good reasoning and I'm very much eager to know. I will look into them. :)

**Comment by underlineGalaxy** [comment]
> > The other answers didn't really feel Pythonic, so I thought of sharing mine :P
> > Also little typo fix in the end
> 
> Please let me know which answer's you didn't find pythonic. I believe you have good reasoning and I'm very much eager to know. I will look into them. :)

From my programming teacher I tend to take the following principles:
1 - Do not repeat yourself
2 - Prefer readable and easy to understand code
3 - Prefer faster/easier methods (like existing libraries), but not at the cost of point 2
4 - Now this is a personal one and you might find it funny but a code has to "feel right". On this exercise, anything that uses the "cnt" logic just doesn't "feel right" for me.

1 - breaks 1
2 - all the "and" in the if function on line -4 doesn't feel right, breaks 3 for not using regex 
3 - This is actually good but uses the cnt logic
4 - breaks 1
5 - It kind of breaks 2, however it's the best use of the 3rd principle. A regex function that has all the requirements is hard to make and read, however it is definitely faster and more compact than having different regex'es for different requirements. It's a two way knife. It's still a good solution though.

**Comment by darkprinx** [comment]
The reasoning you mentioned is true indeed. Can you please help me out to fix them in the way you described it? It will be a great help :) and yes, sorry for the late reply. Thank you.

**Comment by underlineGalaxy** [comment]
> The reasoning you mentioned is true indeed. Can you please help me out to fix them by a pull request in the way you described it? It will be a great help :) and yes, sorry for the late reply. Thank you.

Sorry for the (Very) late reply too. I'd say keep them as is, normally I tend to understand the logic of the exercise through those answers and even if they're bad real world examples they still help me. I just liked this question in particular to the point of adding my own answer which could fit into a real world scenario.

**Pull request merged**
